
utter = [
    """
FA 관련은 학칙을 확인하는게 가장 정확합니다!
관련 부분은 다음과 같습니다.

제25조 (FA제도) ① 한 학기 동안 학생이 수강하는 과목에 대하여 결석허용 한계를 정하고 이를 초과할 경우에는 그 과목의 성적은 FA로 기록되며 과목낙제가 된다.
   ② 매 과목당 결석 허용 회수는 한 학기를 통산하여 주당 수업시간수의 두 배까지이다. 즉, 한 학기에 주당 3시간 과목은 6시간, 주당 2시간 과목은 4시간까지 결석이 허용된다. 3회의 지각은 한 번의 결석으로 환산된다. 
   ③ 졸업하는 마지막 학기의 결석 허용한계는 위 한계의 두 배이다. (여기서 졸업하는 학기란 졸업예정자로 확정된 학기를 말한다.)
   ④ 학생의 결석회수가 위의 허용한계에 도달될 경우, 이를 인터넷을 통하여 개별적으로 공고하여 해당 학생에게 경고한다. 모든 학생은 자신의 과목별 결석 및 지각회수를 기록 보관하여 FA경고에 항시 유의하여야 한다.<개정 2012.2.22>
   ⑤ 위의 결석허용 한계를 초과한 학생은 이를 공고하며, 해당과목의 성적은 과목낙제인 FA로 표시된다.<개정 2022.6.14>
   ⑥ 강의와 실험실습으로 구성된 과목에 있어서는 출결점검을 구분하여 처리하며 강의와 실험실습 중 어느 하나에서 FA를 받을 경우 그 과목 전체 성적이 FA가 된다.
   ⑦ 졸업예정 학기에 조기 취업 및 입사시험으로 인하여 부득이 제③항의 결석 허용한계 초과 시, 학생이 취업확인서(지정 서식)를 해당 기업(또는 기관)의 확인을 받아 학사지원팀에 제출할 경우, 담당교수 재량에 의하여 해당 근무기간을 출석으로 대체 인정할 수 있다. <신설 2016.10.14>
   ⑧ 제⑦항의 경우, 담당교수는 해당 교육과정 이수를 인정할만한 수업 과제나 시험을 통하여 평가를 하고, 이에 상응하는 성적을 부여하여야 한다. 다만, 이 경우 성적은 B+ 이하로 부여함을 원칙으로 한다. <신설 2016.10.14>

제26조 (유고결석) ① 다음 각 호의 사유에 의하여 결석하게 될 경우 사고발생전이나 발생 즉시 또는 부득이한 경우 발생일로부터 7일 이내에 증빙서류를 첨부하여 제1전공 소속 대학행정팀에 유고결석계를 제출하면 각 사유별 결석허용기간에 대해서는 결석으로 간주하지 않는다.<개정 2007.2.6., 2022.03.23>
    1. 부모 및 형제자매 사망, 본인 결혼시 7일(휴일 포함), 조부모 사망시 3일(장례일정이 3일 초과시 장례일까지/휴일 포함) <개정 2013.7.11, 2016.12.23>
    2. 입원치료, 전염성 질환 등 의사 소견상 등교가 불가능한 질병 또는 상해 치료의 경우 2주 이내 <개정 2013.7.11, 2016.12.23>
    3. 징병검사 등 병역관계 및 예비군훈련의 경우 통지서에 명기된 일수 <개정 2016.12.23>
    4. 학교현장실습 및 각 학과 학술여행, 야외실습, 기타 본교 주관 교육프로그램 참가의 경우 해당기간
    5. <삭제 2016.12.23>
    6. 정부기관의 요청에 의한 특별회합의 경우 해당시간
    7. 학생활동부서 임원의 국제회합 및 이에 준하는 경우 해당시간
    8. 신문 발간을 위한 정·부편집장의 긴급작업의 경우 해당시간
    9. 학교의 요청에 따른 교내·외 중요행사 참여의 경우 해당기간
    10. 긴급한 재난 재해, 1급 법정 감염병 및 기타 감염병 감염 또는 감염 의심 등 총장이 지정한 사유의 경우 해당 기간 <신설 2022.6.14.>
    11. 본인 출산시 20일, 배우자의 출산시 10일(출산일을 포함하여 출산전후로 신청 가능) <신설 2023.05.11>
       ② 다만, 제7호 및 제8호는 학생문화처장의 사전 승인을 얻은 경우에 한하여 제출할 수 있으며, 제9호는 총장의 승인을 받은 경우에 한하여 허용한다. <개정 2016.12.23>
       ③ 다음 각 호의 1에 해당하는 경우에는 유고결석으로 인정될 수 없다. 
            1. 신문기자의 신문발간 작업
            2. 각 동아리의 연습 및 공연
            3. 타교와의 운동 시합
            4. 교통편의 연착
            5. <삭제 2013.7.11>
            6. 가족의 병고
            7. 가사 및 개인사정
   [전문개정 2006.2.14]

출처: https://www.sogang.ac.kr/gopage/goboard12.jsp?bbsConfigFK=170&pkid=500062
"""
]

variables = []
