utter = [
    """
재수강 제도에 대해서는 학칙을 확인하는게 가장 정확합니다.
관련 부분은 다음과 같습니다.

제15조 (재이수) 
   ① 이미 이수한 교과목을 재이수할 수 있다. 재이수의 경우 전(前) 성적의 학적부 기록은 R(Re-registered)로 대체되며 새로이 취득한 성적으로 총성적평점평균(CGPA)을 계산한다.
   ② 재이수하여 취득한 성적은 “A⁻ ”를 초과할 수 없다. <개정 2006.2.14., 2014.12.11>
   ③ 재이수 과목은 본 시행세칙 제12조 ⑤항에 따른 수강신청 가능학점에 포함된다.<개정 2009.5.26., 2020.06.08>
   ④ 지도교수 및 학과장(전공주임교수)은 수강신청학점의 제한을 둘 수도 있다.<개정 2006.2.14>
   ⑤ 과목번호, 과목명 및 과목내용이 반드시 동일하여야 한다. 다만, 8학기 이상 재학생에 한하여 재이수할 과목이 당해 학기를 포함하여 재학한 직전 4학기 이내에 개설되지 않은 경우, 재이수 대상과목을 개설하는 전공 학과장의 요청으로 당해 학기에 개설된 타 과목으로 재이수 할 수 있다.<개정 2020.12.15.>
   ⑥ 이미 취득한 과목과 과목번호, 과목명이 동일한 과목은 신규수강과목으로 학점을 취득할 수 없다.
   ⑦ 재이수는 재학 중 8회 이내로 제한한다. 다만 계절수업 중 재이수는 재학 중 8회에 산입하지 않는다.<신설 2006.2.14, 개정 2014.12.11, 2020.06.08>
   ⑧ <신설 2007.2.6.><삭제 2023.09.06>
   ⑨ <삭제 2020.06.08>
   ⑩ 이미 이수한 교과목 중 ‘S(Successful)’ 등급을 받은 과목은 재이수할 수 없다.<2015.10.29>
   ⑪ 편입생이 전적대학에서 이수한 과목 중 본교 교과목으로 인정받은 과목은 재이수할 수 없다.<2015.10.29>

출처: https://www.sogang.ac.kr/gopage/goboard12.jsp?bbsConfigFK=170&pkid=500062
"""
]

variables = []
